//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionMovil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datos_preconsulta
    {
        public int id { get; set; }
        public Nullable<int> preconsulta_id { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<decimal> estatura { get; set; }
        public string presion { get; set; }
    
        public virtual preconsulta preconsulta { get; set; }
    }
}
