//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionMovil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class examen
    {
        public int id { get; set; }
        public Nullable<int> diagnostico_id { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual diagnostico diagnostico { get; set; }
    }
}
