//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionMovil.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UHConsultaEntities : DbContext
    {
        public UHConsultaEntities()
            : base("name=UHConsultaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asistente> asistente { get; set; }
        public virtual DbSet<cita> cita { get; set; }
        public virtual DbSet<contraseña> contraseña { get; set; }
        public virtual DbSet<datos_preconsulta> datos_preconsulta { get; set; }
        public virtual DbSet<diagnostico> diagnostico { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<examen> examen { get; set; }
        public virtual DbSet<nutricion> nutricion { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<preconsulta> preconsulta { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tratamiento> tratamiento { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
