//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionMovil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class preconsulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public preconsulta()
        {
            this.datos_preconsulta = new HashSet<datos_preconsulta>();
            this.diagnostico = new HashSet<diagnostico>();
        }
    
        public int id { get; set; }
        public Nullable<int> cita_id { get; set; }
        public Nullable<int> asistente_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string motivo { get; set; }
    
        public virtual asistente asistente { get; set; }
        public virtual cita cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datos_preconsulta> datos_preconsulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diagnostico> diagnostico { get; set; }
    }
}
